# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: البدایہ والنہایہ جلد دوم
author: علامہ حافظ ابوالفدا عماد الدین ابن کثیر (مترجم؛ پروفیسر کوکب شادانی )
copyright: 

sphinx:
  config:
    language: ur
